project:
  type: website

website:
  title: "org.allnix.js"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: docked
    contents:
      - learn_javascript.qmd
      - react_quickly_note.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    # https://quarto.org/docs/output-formats/html-code.html#code-filename
    code-block-border-left: false
    code-block-bg: true
    highlight-style: pygments



