project:
  type: website

website:
  title: "org.allnix.js"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - react_quickly_note.qmd
      - about.qmd
  sidebar:
    style: docked
    contents:
      - react_quickly_note.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



